version: "3"

services:
  database:
    image: postgres
    container_name: database_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=expressprisma
    volumes:
      - pg-data:/var/lib/postgresql/data

    networks:
      - test-network
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - test-network
  app:
    image: application
    build:
      context: .
    container_name: app_api
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    depends_on:
      - database
      - redis
    networks:
      - test-network
volumes:
  pg-data:
    driver: local
  redis-data:
    driver: local

networks:
  test-network:
    driver: bridge
